# Generated by Django 3.2.2 on 2021-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0004_auto_20210524_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default="{% static 'RecursosWebApp/img/200.gif %}", null=True, upload_to='posts', verbose_name='Imagen'),
        ),
    ]
