# Generated by Django 3.2.2 on 2021-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/posts/200.gif', null=True, upload_to='posts', verbose_name='Imagen'),
        ),
    ]
