# Generated by Django 3.2.2 on 2021-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0007_auto_20210524_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/posts/200.gif', upload_to='posts', verbose_name='Imagen'),
        ),
    ]
