# Generated by Django 3.2.2 on 2021-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0011_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='profile_pic',
            field=models.ImageField(default='/profile_pics/profile-default.svg', upload_to='profile_pics', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='webpage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sitio Web'),
        ),
    ]
