# Generated by Django 3.2.2 on 2021-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0013_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
