# Generated by Django 3.2.2 on 2021-05-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0014_alter_perfil_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
    ]
