# Generated by Django 3.2.2 on 2021-05-26 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecursosWebApp', '0015_alter_perfil_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='name',
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='auth.user'),
            preserve_default=False,
        ),
    ]
