# Generated by Django 3.2.2 on 2021-05-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0016_auto_20210526_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='body',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
