# Generated by Django 3.2.2 on 2021-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosWebApp', '0019_perfil_from_signal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['created'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profile_pic',
            field=models.ImageField(default='/profile_pics/user_icon_rpzpcr.png', upload_to='profile_pics', verbose_name='Foto de perfil'),
        ),
    ]
